In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

np.random.seed(4)

def simple_statistic(i,j,n,p,Y):
    return np.sum((Y[i,:] - Y[j,:])**2 - 2) / (n**(p-1))

def two_hop_statistic(i,j,n,p,Y, Omega, x):
    # print('Calculating the statistic for i: ' + str(i) + ' and j: ' + str(j))

    stat = 0
    num_entries = 0
    for l in range(n):
        if l != i and l != j:

            # print('Using the index l : ' + str(l))

            it_one = np.nditer(Y[l, :], flags=['multi_index'])
            while not it_one.finished:
                index_one = (l,) + it_one.multi_index
                it_two = np.nditer(Y[l, :], flags=['multi_index'])
                while not it_two.finished:
                    index_two = (l,) + it_two.multi_index
                    # print('index one: ' + str(index_one))
                    # print('index two: ' + str(index_two))
                    if Omega[index_one] and ~Omega[index_two] == 0:
                        stat += Y[index_one] * Y[index_two] * Y[(i,) + it_one.multi_index] * Y[(j,) + it_two.multi_index]
                        num_entries += 1
                    it_two.iternext()
                it_one.iternext()
    return stat / num_entries

def two_hop_statistic_new(i,j,n,p,Y, Omega, x):
    # print('Calculating the statistic for i: ' + str(i) + ' and j: ' + str(j))

    stat = 0
    num_entries = 0
    for l in range(n):
        if l != i and l != j:
            # print('Using the index l : ' + str(l))
            it_one = np.nditer(Y[l, :], flags=['multi_index'])
            while not it_one.finished:
                index_one = (l,) + it_one.multi_index
                it_two = np.nditer(Y[l, :], flags=['multi_index'])
                while not it_two.finished:
                    index_two = (l,) + it_two.multi_index
                    # print('index one: ' + str(index_one))
                    # print('index two: ' + str(index_two))
                    if Omega[it_one.multi_index] == 1 and Omega[it_two.multi_index] == 0:
                        stat += Y[index_one] * Y[index_two] * Y[(i,) + it_one.multi_index] * Y[(j,) + it_two.multi_index]
                        num_entries += 1
                    it_two.iternext()
                it_one.iternext()
    return stat / num_entries


In [76]:
p = 4
num_iters = 2
lam = 0.5
prob = .5


n = 3
size_list = []
for _ in range(p):
    size_list.append(n)
sign = 0
Omega = np.zeros(size_list[1:], dtype='bool')
it = np.nditer(Omega, flags=['multi_index'])
while not it.finished:
    index = it.multi_index
    Omega[index] = sign
    sign = 1 - sign
    it.iternext()

x = 2*(np.random.binomial(1, prob, n)-.5)
# print(x)
Y = np.tensordot(x,x, axes=0)
for k in range(p-2):
    Y = np.tensordot(Y, x, axes=0)
# Y = lam*Y + np.random.normal(0,1,size_list)
Y = lam*Y


In [77]:
x

array([-1., -1.,  1.])

In [81]:
Y

array([[[[ 0.5,  0.5, -0.5],
         [ 0.5,  0.5, -0.5],
         [-0.5, -0.5,  0.5]],

        [[ 0.5,  0.5, -0.5],
         [ 0.5,  0.5, -0.5],
         [-0.5, -0.5,  0.5]],

        [[-0.5, -0.5,  0.5],
         [-0.5, -0.5,  0.5],
         [ 0.5,  0.5, -0.5]]],


       [[[ 0.5,  0.5, -0.5],
         [ 0.5,  0.5, -0.5],
         [-0.5, -0.5,  0.5]],

        [[ 0.5,  0.5, -0.5],
         [ 0.5,  0.5, -0.5],
         [-0.5, -0.5,  0.5]],

        [[-0.5, -0.5,  0.5],
         [-0.5, -0.5,  0.5],
         [ 0.5,  0.5, -0.5]]],


       [[[-0.5, -0.5,  0.5],
         [-0.5, -0.5,  0.5],
         [ 0.5,  0.5, -0.5]],

        [[-0.5, -0.5,  0.5],
         [-0.5, -0.5,  0.5],
         [ 0.5,  0.5, -0.5]],

        [[ 0.5,  0.5, -0.5],
         [ 0.5,  0.5, -0.5],
         [-0.5, -0.5,  0.5]]]])

In [82]:
Y.shape

(3, 3, 3, 3)

In [83]:
Omega.shape

(3, 3, 3)

In [84]:
Omega

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [False,  True, False]]])

Omega[0,1\

In [85]:
Omega[1,0]

array([ True, False,  True])

In [86]:
Y[0,1,0]

array([ 0.5,  0.5, -0.5])

In [87]:
i = 0
j = 1

In [28]:
first_vect_index = np.ones(n, dtype='bool')

In [88]:
first_vect_index
first_vect_index[i] = False
first_vect_index[j] = False

In [30]:
Y

array([[[[ 1.11136545, -0.60558404,  0.33783635],
         [ 2.58787087,  1.41484096, -0.77620335],
         [ 0.2965119 , -1.64379857,  1.00991978]],

        [[-0.8474603 ,  0.4906399 , -0.63070464],
         [ 1.30208661,  0.19703603,  0.70200259],
         [-0.69674528,  0.3365287 ,  1.28660228]],

        [[-2.34087587, -0.46245251,  0.53592805],
         [-1.27873992, -0.32058929, -0.95553433],
         [ 1.05618522,  1.00977885, -0.19955446]]],


       [[[ 2.97658416,  0.8523434 , -0.432529  ],
         [-0.2322647 ,  0.79714121, -1.4617768 ],
         [ 0.77181862, -1.14764453,  0.65846954]],

        [[ 2.49008302,  1.66418756, -0.25733984],
         [ 1.8799201 ,  0.44544129,  0.29523395],
         [-0.48091004, -1.40543814,  0.93027133]],

        [[ 0.43465006, -0.84610187, -0.59712188],
         [-1.02819607, -2.87977527, -0.10768369],
         [-0.57529009,  2.52240507, -1.0648753 ]]],


       [[[-2.04292905,  0.37084178,  0.32478947],
         [-0.45139699, -0.3113538 

In [31]:
Y[Omega]

array([[ 2.58787087,  1.41484096, -0.77620335],
       [-0.8474603 ,  0.4906399 , -0.63070464],
       [-0.69674528,  0.3365287 ,  1.28660228],
       [-1.27873992, -0.32058929, -0.95553433],
       [ 2.97658416,  0.8523434 , -0.432529  ],
       [ 0.77181862, -1.14764453,  0.65846954],
       [ 1.8799201 ,  0.44544129,  0.29523395],
       [ 0.43465006, -0.84610187, -0.59712188],
       [-0.57529009,  2.52240507, -1.0648753 ],
       [-0.45139699, -0.3113538 ,  0.70931349],
       [-0.99581852, -0.67146461, -0.4443686 ],
       [ 1.11474063,  0.37343141,  1.07887425],
       [ 0.58126377,  0.25947582,  1.53217933]])

In [32]:
mat_one = Y[first_vect_index,Omega] # Y[l,h]

In [33]:
mat_two = Y[first_vect_index, ~Omega] # Y[l, h']

In [125]:
Y[i, Omega]
Y[j, ~Omega]

array([ 1.06373477,  0.70218012, -0.21522547, -0.24738768, -1.9598148 ])

In [36]:
mat_two.shape

(14,)

In [37]:
mat_one.shape

(13,)

In [103]:
def two_hop_statistic_new(i,j,n,p,Y, Omega, x):
    print('Calculating the statistic for i: ' + str(i) + ' and j: ' + str(j))

    stat = 0
    it_one = np.nditer(Omega, flags=['multi_index'])
    while not it_one.finished:
        it_two = np.nditer(Omega, flags=['multi_index'])
        while not it_two.finished:

            first_vect_index = np.ones(n, dtype='bool')
            first_vect_index[i] = False
            first_vect_index[j] = False      

            print('index one: ' + str(it_one.multi_index))
            print('index two: ' + str(it_two.multi_index))
            print(first_vect_index)
            print(Y[first_vect_index, it_one.multi_index].shape)
            if Omega[it_one.multi_index] == 1 and Omega[it_two.multi_index] == 0:
                stat += Y[(i,) + it_one.multi_index] * Y[(j,) + it_two.multi_index] * np.sum(Y[first_vect_index, it_one.multi_index] * Y[first_vect_index, it_two.multi_index])
            it_two.iternext()
        it_one.iternext()
    return stat


In [104]:
two_hop_statistic_new(0,2,n,p,Y,Omega,x)

Calculating the statistic for i: 0 and j: 2
index one: (0, 0, 0)
index two: (0, 0, 0)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 0, 1)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 0, 2)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 1, 0)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 1, 1)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 1, 2)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 2, 0)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 2, 1)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (0, 2, 2)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (1, 0, 0)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (1, 0, 1)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (1, 0, 2)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)
index two: (1, 1, 0)
[False  True False]
(3, 3, 3)
index one: (0, 0, 0)

index one: (2, 2, 2)
index two: (2, 0, 1)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 0, 2)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 1, 0)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 1, 1)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 1, 2)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 2, 0)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 2, 1)
[False  True False]
(3, 3, 3)
index one: (2, 2, 2)
index two: (2, 2, 2)
[False  True False]
(3, 3, 3)


-3.375

In [98]:
x[0]*x[1]

1.0

In [99]:
x[0]*x[2]

-1.0

In [105]:
index_one = (2,0,2)
index_two = (1,0,0)

In [113]:
Y[[1,1,0], index_one]

array([[[-0.5, -0.5,  0.5],
        [-0.5, -0.5,  0.5],
        [ 0.5,  0.5, -0.5]],

       [[ 0.5,  0.5, -0.5],
        [ 0.5,  0.5, -0.5],
        [-0.5, -0.5,  0.5]],

       [[-0.5, -0.5,  0.5],
        [-0.5, -0.5,  0.5],
        [ 0.5,  0.5, -0.5]]])

In [112]:
vec_one = [True, True, False]